version: "3"

services:
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "9427:5432"

  redis:
    image: redis:6-alpine
    ports:
      - "9428:6379"

  proxy:
    image: wafflehacks/dev-proxy
    build: ./dev-proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
