version: "3"

services:
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "9427:5432"

  redis:
    image: redis:6-alpine
    ports:
      - "9428:6379"

  nats:
    image: nats:2.8.4-scratch
    command:
      - -a=0.0.0.0
      - -p=4222
      - --jetstream
    ports:
      - "9442:4222"

  mailer:
    image: wafflehacks/mailer:latest
    environment:
      MAILER_ADDRESS: 0.0.0.0
      MAILER_LOG_LEVEL: info
      MAILER_DEVELOPMENT: "no"
      MAILER_PROVIDERS: debug
      MAILER_PROVIDER_DEBUG_TYPE: debug
      MAILER_PROVIDER_DEBUG_FAILURE_RATE: "0"
      MAILER_PROVIDER_DEBUG_SHOW_BODY: "yes"
    ports:
      - "9464:8000"  # HTTP
      - "9465:9000"  # gRPC

  jaeger:
    image: jaegertracing/all-in-one:1.34
    ports:
      - "9431:6831/udp"
      - "9486:16686"
      - "9411:9411"
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: :9411
