# fly.toml app configuration file generated for application-portal-mjml on 2023-04-19T16:11:33-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "application-portal-mjml"
primary_region = "yyz"

[build]
   image = "public.ecr.aws/wafflehacks/application-portal-mjml:sha-SHORT_SHA"

[deploy]
  strategy = "rolling"

[env]
  HOST = "0.0.0.0"
  PORT = "8000"

  OTEL_ENABLE = "yes"
  OTEL_DEBUG = "no"
  OTEL_SERVICE_NAME = "application-portal/mjml"
  OTEL_EXPORTER_OTLP_ENDPOINT = "https://api.honeycomb.io"

[checks]
  [checks.alive]
    type = "http"
    port = 8000
    method = "get"
    path = "/health"
    protocol = "http"

    grace_period = "15s"
    interval = "15s"
    restart_limit = 0
    timeout = "3s"
