"""add other gender option

Revision ID: 03e3fe94e1ed
Revises: d32dcfa45423
Create Date: 2022-04-17 22:13:00.167426+00:00

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "03e3fe94e1ed"
down_revision = "d32dcfa45423"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE gender ADD VALUE 'OTHER'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Delete any rows referencing the enum state
    op.execute("DELETE FROM applications WHERE gender = 'OTHER'")

    # Rename the old type
    op.execute("ALTER TYPE gender RENAME TO gender_old")

    # Create a new type with the state removed
    op.execute("CREATE TYPE gender AS ENUM('MALE', 'FEMALE', 'NON_BINARY')")

    # Change the colum type
    op.execute(
        "ALTER TABLE applications ALTER COLUMN gender TYPE gender USING gender::text::gender"
    )

    # Remove the old type
    op.execute("DROP TYPE gender_old")
    # ### end Alembic commands ###
