"""add application flagged

Revision ID: 108677b68119
Revises: 0cf086aa6b96
Create Date: 2022-05-30 21:45:48.595341+00:00

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "108677b68119"
down_revision = "0cf086aa6b96"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applications",
        sa.Column(
            "flagged",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    # ### end Alembic commands ###

    # Determine if an any applications should be flagged based on their graduation year and birthdate
    # The conditions for being flagged are:
    #   - graduation year is less than the last year (this is to allow new grads to participate)
    #   - age is less than 13 years
    op.execute(
        "UPDATE applications "
        "SET flagged = true WHERE "
        "graduation_year < date_part('year', current_date) - 1 OR "
        "to_date(date_of_birth, 'DD-MM-YYYY') <= current_date - '13 years'::interval"
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applications", "flagged")
    # ### end Alembic commands ###
