"""add providers table

Revision ID: 111fd0c489b8
Revises: cedc0da31c8f
Create Date: 2023-04-17 23:38:03.878796+00:00

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "111fd0c489b8"
down_revision = "cedc0da31c8f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "providers",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("icon", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("client_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "authorization_endpoint", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("token_endpoint", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "user_info_endpoint", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("scope", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("client_secret", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("slug"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("providers")
    # ### end Alembic commands ###
