"""delete applications on participant delete

Revision ID: 11505f38b11f
Revises: 32c905599391
Create Date: 2022-04-02 22:27:13.162802+00:00

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "11505f38b11f"
down_revision = "32c905599391"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "applications_participant_id_fkey", "applications", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "applications",
        "participants",
        ["participant_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "applications", type_="foreignkey")
    op.create_foreign_key(
        "applications_participant_id_fkey",
        "applications",
        "participants",
        ["participant_id"],
        ["id"],
    )
    # ### end Alembic commands ###
