"""add link column to events

Revision ID: 185da460c739
Revises: 76b084e37b34
Create Date: 2023-06-11 06:01:59.803646+00:00

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "185da460c739"
down_revision = "76b084e37b34"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events", sa.Column("link", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "link")
    # ### end Alembic commands ###
