"""add school review flag

Revision ID: 204f901e04ea
Revises: 41f361ac6a74
Create Date: 2022-06-07 07:09:26.865100+00:00

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "204f901e04ea"
down_revision = "41f361ac6a74"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schools",
        sa.Column(
            "needs_review",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schools", "needs_review")
    # ### end Alembic commands ###
