"""Add legal agreement flag

Revision ID: 20f5d14a594a
Revises: c7416886f30d
Create Date: 2022-02-15 07:48:27.640531+00:00

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "20f5d14a594a"
down_revision = "c7416886f30d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applications",
        sa.Column("legal_agreements_acknowledged", sa.Boolean(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applications", "legal_agreements_acknowledged")
    # ### end Alembic commands ###
