"""recipient use composite primary key

Revision ID: 2693c4ff6368
Revises: 39df5dce6493
Create Date: 2022-05-06 20:39:56.757617+00:00

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "2693c4ff6368"
down_revision = "39df5dce6493"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "recipients", "message_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("recipients", "id")

    op.create_primary_key(None, "recipients", ["message_id", "group"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("recipients_pkey", "recipients")

    op.add_column(
        "recipients", sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False)
    )
    op.alter_column(
        "recipients", "message_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
