"""remove legal agreements table

Revision ID: 378a9b9a491b
Revises: c2d6f3f46dfa
Create Date: 2022-04-19 08:34:56.276261+00:00

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "378a9b9a491b"
down_revision = "c2d6f3f46dfa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("legal_agreements")
    op.drop_constraint(
        "applications_school_id_fkey", "applications", type_="foreignkey"
    )
    op.create_foreign_key(None, "applications", "schools", ["school_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "applications", type_="foreignkey")
    op.create_foreign_key(
        "applications_school_id_fkey",
        "applications",
        "schools",
        ["school_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_table(
        "legal_agreements",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("content", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="legal_agreements_pkey"),
    )
    # ### end Alembic commands ###
