"""timezone aware timestamps

Revision ID: 39df5dce6493
Revises: 7f51ce38bc57
Create Date: 2022-05-06 19:02:26.667460+00:00

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

from common.database.tables.types import TimeStamp

# revision identifiers, used by Alembic.
revision = "39df5dce6493"
down_revision = "7f51ce38bc57"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("messages", "created_at", type_=TimeStamp(timezone=True))
    op.alter_column("messages", "updated_at", type_=TimeStamp(timezone=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("messages", "created_at", type_=TimeStamp())
    op.alter_column("messages", "updated_at", type_=TimeStamp())
    # ### end Alembic commands ###
