"""add school abbreviations and acronyms

Revision ID: 41f361ac6a74
Revises: c1b1ed99e50d
Create Date: 2022-06-07 03:48:15.445488+00:00

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "41f361ac6a74"
down_revision = "c1b1ed99e50d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schools",
        sa.Column(
            "abbreviations",
            postgresql.ARRAY(sqlmodel.sql.sqltypes.AutoString()),
            nullable=False,
            server_default=sa.text("array[]::varchar[]"),
        ),
    )
    op.add_column(
        "schools",
        sa.Column(
            "alternatives",
            postgresql.ARRAY(sqlmodel.sql.sqltypes.AutoString()),
            nullable=False,
            server_default=sa.text("array[]::varchar[]"),
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schools", "alternatives")
    op.drop_column("schools", "abbreviations")
    # ### end Alembic commands ###
