"""add swag tiers

Revision ID: 49a35dc6c31d
Revises: 02338256c6aa
Create Date: 2022-06-01 05:58:25.373228+00:00

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "49a35dc6c31d"
down_revision = "02338256c6aa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "swag_tiers",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("required_attendance", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "participants", sa.Column("swag_tier_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "participants", "swag_tiers", ["swag_tier_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "participants", type_="foreignkey")
    op.drop_column("participants", "swag_tier_id")
    op.drop_table("swag_tiers")
    # ### end Alembic commands ###
