"""add checked in status to participant

Revision ID: 62b0211f43d3
Revises: 5bebce7e47f3
Create Date: 2023-06-17 04:23:16.089372+00:00

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "62b0211f43d3"
down_revision = "5bebce7e47f3"
branch_labels = None
depends_on = None


function = """
CREATE FUNCTION application_portal_set_checked_in_on_accept_function() RETURNS trigger AS $$
    BEGIN
        UPDATE participants SET checked_in = false WHERE id = NEW.participant_id;
        RETURN coalesce(NEW, OLD);
    END;
$$ LANGUAGE plpgsql;
"""

trigger = """
CREATE TRIGGER application_portal_set_checked_in_on_accept_trigger
    AFTER UPDATE OF status ON applications
    FOR EACH ROW
    WHEN ( NEW.status = 'ACCEPTED' )
    EXECUTE FUNCTION application_portal_set_checked_in_on_accept_function();
"""


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("participants", sa.Column("checked_in", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    op.execute(
        "UPDATE participants SET checked_in = false WHERE id IN "
        "(SELECT participant_id FROM applications WHERE status = 'ACCEPTED')"
    )

    op.execute(function)
    op.execute(trigger)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("participants", "checked_in")
    # ### end Alembic commands ###

    op.execute("DROP TRIGGER application_portal_set_checked_in_on_accept_trigger")
    op.execute("application_portal_set_checked_in_on_accept_function")
