"""convert country to string

Revision ID: 6369ca71dc38
Revises: 8d04b7943264
Create Date: 2022-04-18 06:17:29.348172+00:00

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "6369ca71dc38"
down_revision = "8d04b7943264"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "applications_country_id_fkey", "applications", type_="foreignkey"
    )
    op.drop_table("countries")
    op.add_column(
        "applications",
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.drop_column("applications", "country_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "countries",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="countries_pkey"),
    )
    op.add_column(
        "applications",
        sa.Column("country_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        None,
        "applications",
        "countries",
        ["country_id"],
        ["id"],
    )
    op.drop_column("applications", "country")
    # ### end Alembic commands ###
