"""add rendered to messages

Revision ID: 7563cb70be2d
Revises: f33cced0cb75
Create Date: 2022-05-14 10:06:18.749900+00:00

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "7563cb70be2d"
down_revision = "f33cced0cb75"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column(
            "rendered",
            sqlmodel.sql.sqltypes.AutoString(),
        ),
    )
    # ### end Alembic commands ###

    # Set the rendered value to the current content and then make it non-null
    op.execute("UPDATE messages SET rendered = content")
    op.alter_column("messages", "rendered", nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "rendered")
    # ### end Alembic commands ###
