"""add exports table

Revision ID: 76b084e37b34
Revises: 8b11d0c53677
Create Date: 2023-06-05 18:41:25.435224+00:00

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

from common.database.tables.types import TimeStamp

# revision identifiers, used by Alembic.
revision = "76b084e37b34"
down_revision = "8b11d0c53677"
branch_labels = None
depends_on = None

export_status = sa.Enum("PROCESSING", "COMPLETED", "FAILED", name="export_status")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exports",
        sa.Column("status", export_status, server_default="PROCESSING", nullable=False),
        sa.Column("created_at", TimeStamp(timezone=True), nullable=False),
        sa.Column("finished_at", TimeStamp(timezone=True), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("requester", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("file", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("exports")
    export_status.drop(op.get_bind())
    # ### end Alembic commands ###
