"""collect participant phone number

Revision ID: 98708b2dcb89
Revises: 7563cb70be2d
Create Date: 2022-05-15 07:19:48.421325+00:00

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "98708b2dcb89"
down_revision = "7563cb70be2d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applications",
        sa.Column("phone_number", sqlmodel.sql.sqltypes.AutoString()),
    )
    # ### end Alembic commands ###

    # Set the phone number to an empty string for any existing records and then make it non-null
    op.execute("UPDATE applications SET phone_number = ''")
    op.alter_column("applications", "phone_number", nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applications", "phone_number")
    # ### end Alembic commands ###
