"""add application notes

Revision ID: a2327cf14296
Revises: 9ff5970188bf
Create Date: 2022-05-29 00:57:06.169564+00:00

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "a2327cf14296"
down_revision = "9ff5970188bf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applications",
        sa.Column(
            "notes",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="",
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applications", "notes")
    # ### end Alembic commands ###
