"""add participant is admin flag

Revision ID: b1316c845fab
Revises: a85d78552b07
Create Date: 2023-04-18 19:23:20.664777+00:00

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "b1316c845fab"
down_revision = "a85d78552b07"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "participants",
        sa.Column(
            "is_admin",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("participants", "is_admin")
    # ### end Alembic commands ###
