"""timezone aware timestamps for applications

Revision ID: b5ac23c43648
Revises: 2693c4ff6368
Create Date: 2022-05-07 21:28:10.677535+00:00

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

from common.database.tables.types import TimeStamp

# revision identifiers, used by Alembic.
revision = "b5ac23c43648"
down_revision = "2693c4ff6368"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("applications", "created_at", type_=TimeStamp(timezone=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("applications", "created_at", type_=TimeStamp())
    # ### end Alembic commands ###
