"""add participant role

Revision ID: bac759e7498c
Revises: 5663152229b0
Create Date: 2023-04-18 04:22:38.801857+00:00

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "bac759e7498c"
down_revision = "5663152229b0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    enum = sa.Enum("Participant", "Sponsor", "Organizer", name="role")
    enum.create(op.get_bind())
    op.add_column(
        "participants",
        sa.Column("role", enum, nullable=False, server_default="Participant"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("participants", "role")
    op.execute("DROP TYPE role")
    # ### end Alembic commands ###
