"""add application status

Revision ID: c2d6f3f46dfa
Revises: f31d5d917595
Create Date: 2022-04-19 05:19:10.554700+00:00

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "c2d6f3f46dfa"
down_revision = "f31d5d917595"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    enum = sa.Enum("PENDING", "REJECTED", "ACCEPTED", name="status")
    enum.create(op.get_bind())
    op.add_column(
        "applications",
        sa.Column(
            "status",
            enum,
            server_default="PENDING",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applications", "status")
    # ### end Alembic commands ###
