"""Add countries

Revision ID: c7416886f30d
Revises: 423e059e8b64
Create Date: 2022-02-12 07:51:13.003045+00:00

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "c7416886f30d"
down_revision = "423e059e8b64"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "countries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("applications", sa.Column("country_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "applications", "countries", ["country_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "applications", type_="foreignkey")
    op.drop_column("applications", "country_id")
    op.drop_table("countries")
    # ### end Alembic commands ###
