"""add settings

Revision ID: cedc0da31c8f
Revises: 204f901e04ea
Create Date: 2022-06-19 19:31:01.151952+00:00

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "cedc0da31c8f"
down_revision = "204f901e04ea"
branch_labels = None
depends_on = None

# The default settings values
values = {"ACCEPTING_APPLICATIONS": "true"}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings",
        sa.Column("key", sa.Enum("ACCEPTING_APPLICATIONS", name="key"), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    # ### end Alembic commands ###

    # Seed the database
    for key, value in values.items():
        op.execute(f"INSERT INTO settings (key, value) VALUES ('{key}', '{value}')")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("settings")
    # ### end Alembic commands ###
