"""add messages

Revision ID: d2388da5bbfd
Revises: 3f3fbcf548e9
Create Date: 2022-05-04 21:49:29.234380+00:00

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

from common.database.tables.types import TimeStamp

# revision identifiers, used by Alembic.
revision = "d2388da5bbfd"
down_revision = "3f3fbcf548e9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column(
            "created_at",
            TimeStamp(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            TimeStamp(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("sent", sa.Boolean(), nullable=False),
        sa.Column("subject", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recipients",
        sa.Column("message_id", sa.Integer(), nullable=True),
        sa.Column(
            "group",
            sa.Enum(
                "EVERYONE",
                "APPLICATION_COMPLETE",
                "APPLICATION_INCOMPLETE",
                "STATUS_ACCEPTED",
                "STATUS_DENIED",
                "STATUS_PENDING",
                name="group",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recipients")
    op.drop_table("messages")
    # ### end Alembic commands ###
