"""remove participant id sequence

Revision ID: d32dcfa45423
Revises: 7afacd80d932
Create Date: 2022-04-04 17:59:37.231522+00:00

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "d32dcfa45423"
down_revision = "7afacd80d932"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("participants", "id", server_default=None)
    op.execute(str(sa.schema.DropSequence(sa.schema.Sequence("participants_id_seq"))))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(str(sa.schema.CreateSequence(sa.schema.Sequence("participants_id_seq"))))
    op.alter_column(
        "participants",
        "id",
        server_default=sa.schema.Sequence("participants_id_seq").next_value(),
    )
    # ### end Alembic commands ###
