"""add automated message triggers

Revision ID: eb8fe5a0a086
Revises: b5ac23c43648
Create Date: 2022-05-08 06:15:42.355873+00:00

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

from common.database.tables.message_trigger import MessageTriggerType

# revision identifiers, used by Alembic.
revision = "eb8fe5a0a086"
down_revision = "b5ac23c43648"
branch_labels = None
depends_on = None

# Ad-hoc table for insertion
table = sa.table(
    "message_triggers",
    sa.column("message_id", sa.Integer),
    sa.column("trigger", sa.Enum(MessageTriggerType)),
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_triggers",
        sa.Column(
            "trigger",
            sa.Enum(
                "SIGN_UP",
                "APPLICATION_SUBMITTED",
                "APPLICATION_ACCEPTED",
                "APPLICATION_REJECTED",
                "INCOMPLETE_APPLICATION_24H",
                "INCOMPLETE_APPLICATION_7D",
                name="messagetriggertype",
            ),
            nullable=False,
        ),
        sa.Column("message_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("trigger"),
    )
    # ### end Alembic commands ###

    op.bulk_insert(
        table,
        [
            {"message_id": None, "trigger": trigger.name}
            for trigger in MessageTriggerType
        ],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message_triggers")
    # ### end Alembic commands ###
