"""add webhooks table

Revision ID: ef1249d3aa86
Revises: b1316c845fab
Create Date: 2023-05-18 22:48:20.157007+00:00

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "ef1249d3aa86"
down_revision = "b1316c845fab"
branch_labels = None
depends_on = None

webhook_format = sa.Enum("JSON", "DISCORD", name="webhook_format")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webhooks",
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("format", webhook_format, nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("secret", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("triggered_by", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("webhooks")
    webhook_format.drop(op.get_bind())
    # ### end Alembic commands ###
