"""add is_html to messages

Revision ID: f33cced0cb75
Revises: eb8fe5a0a086
Create Date: 2022-05-14 09:57:51.328368+00:00

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "f33cced0cb75"
down_revision = "eb8fe5a0a086"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column(
            "is_html",
            sa.Boolean(),
            server_default=sa.text("FALSE"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "is_html")
    # ### end Alembic commands ###
