"""add tracks_attendance to events table

Revision ID: fcdb492ecec9
Revises: 782abe80eff2
Create Date: 2023-06-23 20:31:27.668627+00:00

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "fcdb492ecec9"
down_revision = "782abe80eff2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events",
        sa.Column(
            "track_attendance",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "track_attendance")
    # ### end Alembic commands ###
