name: Infrastructure Component

on:
  - push

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: infrastructure/.nvmrc
          registry-url: https://npm.pkg.github.com
          scope: '@wafflehacks'

      - run: yarn
        working-directory: ./infrastructure

      - if: ${{ github.ref == 'refs/heads/main' }}
        run: yarn publish
        working-directory: ./infrastructure
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
