name: Infrastructure Component

on:
  - push

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v3
        with:
          node-version-file: infrastructure/.nvmrc
          registry-url: https://npm.pkg.github.com
          scope: '@wafflehacks'

      - run: yarn --ignore-scripts
        working-directory: ./infrastructure

      - if: github.ref != 'refs/heads/main'
        run: yarn build
        working-directory: ./infrastructure

      - if: github.ref == 'refs/heads/main'
        id: should-publish
        uses: tj-actions/changed-files@v19
        with:
          files: infrastructure

      - if: github.ref == 'refs/heads/main' && steps.should-publish.outputs.any_changed == 'true'
        run: yarn publish
        working-directory: ./infrastructure
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
