name: Docker

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"

jobs:
  applications:
    name: Applications
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        app:
          - registration
          - sync
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/poetry.lock') }}-${{ matrix.app }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ hashFiles('**/poetry.lock') }}-${{ matrix.app }}-
            ${{ runner.os }}-buildx-${{ hashFiles('**/poetry.lock') }}-
            ${{ runner.os }}-buildx-

      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: wafflehacks/application-portal
          tags: |
            type=ref,event=branch,prefix=${{ matrix.app }}-
            type=semver,pattern=${{ matrix.app }}-{{version}}
            type=semver,pattern=${{ matrix.app }}-{{major}}.{{minor}}
            type=semver,pattern=${{ matrix.app }}-{{major}}
            type=sha,prefix=${{ matrix.app }}-
            type=raw,value=${{ matrix.app }}-latest

      - uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: ${{ matrix.app }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # Temp fix for:
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move build cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
