name: Deploy

on:
  - push

jobs:
  containers:
    name: Containers
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        app:
          - api
          - mjml
          - tasks
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/poetry.lock') }}-${{ matrix.app }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ hashFiles('**/poetry.lock') }}-${{ matrix.app }}-
            ${{ runner.os }}-buildx-${{ hashFiles('**/poetry.lock') }}-
            ${{ runner.os }}-buildx-

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: ${{ github.run_id }}
          aws-region: us-east-1

      - uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr
        with:
          registry-type: public

      - uses: docker/setup-buildx-action@v2

      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/wafflehacks/application-portal-${{ matrix.app }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: ${{ matrix.app }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # Temp fix for:
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move build cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    needs: [containers]
    if: github.ref == 'refs/heads/main'
    strategy:
      fail-fast: false
      matrix:
        app:
          - api
          - mjml
          - tasks
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy --remote-only -c fly.${{ matrix.app }}.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}
