name: Lint

on:
  - push

jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: frontend/.nvmrc
          cache: yarn
          cache-dependency-path: frontend/yarn.lock

      - run: yarn install
        working-directory: frontend
      - run: yarn eslint --max-warnings=0 .
        working-directory: frontend

  mjml:
    name: MJML
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - run: cargo fmt --check
        working-directory: mjml
      - run: cargo clippy -- -D warnings
        working-directory: mjml
