name: Lint

on:
  - push

jobs:
  node:
    name: Node
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        package:
          - frontend
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ${{ matrix.package }}/.nvmrc
          cache: yarn
          cache-dependency-path: |
            ${{ matrix.package }}/yarn.lock

      - run: yarn install
        working-directory: ${{ matrix.package }}
      - run: yarn eslint --max-warnings=0 .
        working-directory: ${{ matrix.package }}

  rust:
    name: Rust
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - run: cargo fmt --check
        working-directory: mjml
      - run: cargo clippy -- -D warnings
        working-directory: mjml
