name: Lint

on:
  - push

jobs:
  node:
    name: Node
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        package:
          - frontend
          - mjml
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: |
            ${{ matrix.package }}/yarn.lock

      - run: yarn install
        working-directory: ${{ matrix.package }}
      - run: yarn eslint --max-warnings=0 .
        working-directory: ${{ matrix.package }}
